version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # The following are updated with k8s.io/client-go
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
