builds:
  - ldflags:
      - -s -w -X github.com/clevyr/kubedb/cmd.Version={{.Version}} -X github.com/clevyr/kubedb/cmd.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^:pencil:"
brews:
  - tap:
      owner: clevyr
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "completion", "bash")
      (bash_completion/"{{ .ProjectName }}").write output
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "completion", "zsh")
      (zsh_completion/"_{{ .ProjectName }}").write output
nfpms:
  - id: packages
    formats:
      - deb
      - rpm
    maintainer: Gabe Cook <gabe@clevyr.com>
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/clevyr/
