builds:
  - ldflags:
      - -s -w -X github.com/clevyr/kubedb/cmd.Version={{.Version}} -X github.com/clevyr/kubedb/cmd.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^:pencil:"
brews:
  - tap:
      owner: clevyr
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "completion", "bash")
      (bash_completion/"{{ .ProjectName }}").write output
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "completion", "zsh")
      (zsh_completion/"_{{ .ProjectName }}").write output
