repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
      - id: go-mod-tidy
      - id: go-generate
        name: go-generate-docs
        pass_filenames: false
        args: [./docs.go]
